name: Feature Request
title: "[FEATURE REQUEST]: "
description: Request a feature for the launcher here
labels: [enhancement]
body:
  - type: checkboxes
    id: checkotherissues
    attributes:
      label: "Are you sure that this isn't a duplicate issue from another person?"
      description: "You will agree that; if there's another duplicate issue from another person, this issue form will be closed without planned."
      options:
      - label: "I have searched existing issues and confirmed this is not a duplicate."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe your feature here."
      description: "Provide screenshots or videos of the concept."
      placeholder: "Add a feature about..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "How will this be helpful in a real world?"
      placeholder: "This would make it easier to..."
    validations:
      required: true